name: final project pipeline2

on: 
  push:
    branches: [DEV, QA, main]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with: 
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - run: npm install --save-dev cross-env
      - run: npm install react@18 react-dom@18
      - run: npx browserslist@latest --update-db
      - name: Lint
        run: npm run eslint
      #- name: Build
      #  run: npm run build:ci
      - name: Unit Tests
        run: npm test
      - name: Start app (background)
        run: |
          # run server in background and save PID to file
          nohup npm start > server.log 2>&1 &
          echo $! > server.pid 
      - name: E2E Tests
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.js 
      - name: Run Cypress E2E tests
        run: 
          npm run test:e2e  
      - name: Stop server (always)
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || true
            rm -f server.pid
          fi
          # optional: show last lines of server log for debugging
          tail -n +1 server.log | sed -n '1,200p'