name: final project pipeline2

on: 
  push:
    branches: [DEV, QA, main]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: step1 goes here
        run: echo "testing step1"
      