name: final project pipeline2

on: 
  push:
    branches: [DEV, QA, main]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - run: npm install --save-dev cross-env
      - run: npm install react@18 react-dom@18
      - run: npx browserslist@latest --update-db
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build:ci
      - name: Unit Tests
        run: npm test
      - name: E2E Tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run test:e2e
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60000